### ISSUE TITLE
cargo graph does not work with cargo workspaces

### ISSUE THREAD

**Issue by debris** [kbknapp/cargo-graph#33]
When using workspaces, `Cargo.toml`'s `[root]` is basically just backwards compatibility and no longer points to master crate. This makes graph incomplete, cause it doesn't contain all crates from the workspace.

Full description of an issue can be found here: https://github.com/rust-lang/cargo/issues/3203

**Comment by behnam** [comment]
Is there any plan to fix this?

**Comment by matthiasbeyer** [comment]
I'm interested in this as well!

**Comment by Boscop** [comment]
Please fix this :)

**Comment by remram44** [comment]
#38 fixes this by reading `package.name` from `Cargo.toml` and using that as the root.

**Comment by remram44** [comment]
Bump. I feel like this is an important fix that people have been waiting for. Are there any plans to apply my patch?
