### ISSUE TITLE
Filtering on dev-dependencies not working

### ISSUE THREAD

**Issue by bvssvni** [kbknapp/cargo-graph#4]
`cargo graph --dev-deps=false | dot -Tpng > Cargo.png`

Also tried:

`cargo graph --dev-color red | dot -Tpng > Cargo.png`

**Comment by bvssvni** [comment]
Tested on [Conrod](https://github.com/pistondevelopers/conrod).

The dev dependencies are includes in the graph appear similar to normal dependencies.

**Comment by bvssvni** [comment]
Here is an image of the generated graph with the command:

`cargo graph --manifest-file Cargo.toml --dev-deps=false | dot -Tpng > Cargo.png`

![cargo](https://cloud.githubusercontent.com/assets/1743862/11132681/a1183ca8-8991-11e5-8888-43f433526a90.png)

**Comment by bvssvni** [comment]
`Project::parse_root_deps` looks right.

I wonder whether it should be any filtering in `Project::parse_lock_file` or the filtering is done when rendering the graph.

**Comment by bvssvni** [comment]
Seems that all are added as build dependencies https://github.com/kbknapp/cargo-graph/blob/master/src/project.rs#L111

**Comment by hauleth** [comment]
Same here

Octavo:

![image](https://cloud.githubusercontent.com/assets/291639/11133579/d6dce7f8-8996-11e5-8db3-249f6edee101.png)

**Comment by bvssvni** [comment]
I think that a simple for loop might not be enough to do the filtering.

- All packages depended on by a dev-dependency should count as `DevKind::Dev` unless it is depended on by a dependency
- Packages might come in any order in Cargo.lock

I suggest the following:

1. Loop through all packages, build a `HashMap` storing `Option<DevKind>` per package name.
2. Loop while any entry in the `HashMap` gets changes, checking each dependency per package.
3. The final loop, filtering using the `HashMap`.

**Comment by bvssvni** [comment]
The algorithm will "fill" the graph similar to a paint bucket algorithm, marking the dev-dependencies but overriding them as dependencies if they get are depended on by a normal dependency.

**Comment by kbknapp** [comment]
Thanks for all the input! I'll start looking into this as well. Since I don't use many dev-deps it's difficult to test without picking crates I'm less familiar with. If you find the issue before me, put in a PR, I'm all about some contributors :+1:

**Comment by kbknapp** [comment]
@bvssvni  I think you're correct
